# config.py

GLOBAL_OPENAI_API_KEY = "OPENAI_API_KEY"
GLOBAL_CLAUDE_API_KEY = "CLAUDE_API_KEY"
DEFAULT_OPENAI_MODEL = "gpt-3.5-turbo"
WARNING_BULLETS = "warning_bullets"

SESSION_OPENAI_API_KEY = "SESSION_OPENAI_API_KEY"
SESSION_CLAUDE_API_KEY = "SESSION_CLAUDE_API_KEY"